account/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),

    path('user/<slug:username>', views.user, name="user"),
    path('mypage/', views.mypage, name="mypage"),
    path('follower/<slug:username>', views.follower, name="follower"),
    path('following/<slug:username>', views.following, name="following"),
    path('follow/<slug:username>', views.follow, name="follow"),
    path('unfollow/<slug:username>', views.unfollow, name="unfollow"),
    path('info_setting/', views.info_setting, name="info_setting"),
    path('pw_setting/', views.pw_setting, name="pw_setting"),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
]

hackproject/urls.py
from django.contrib import admin
from django.urls import path, include
from two import views
import account.urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('photoshop/', views.photoshop, name='photoshop'),
    path('photodetail/<int:pk>', views.photodetail, name='photodetail'),
    path('photodetail/<int:pk>/photoscrap', views.photoscrap, name='photoscrap'),
    path('photodetail/<int:pk>/photoscrap_del', views.photoscrap_del, name='photoscrap_del'),
    path('photodetail/<int:pk>/filter/', views.filter, name="filter"),
    path('contest/', views.contest, name='contest'),
    path('contestway/',views.contestway, name='contestway'),
    path('mission/', views.mission, name='mission'),
    path('account/', include(account.urls)),
    path('comment_delete/<int:comment_id>', views.comment_delete, name="comment_delete"),
    path('mission_detail/<int:mission_id>', views.mission_detail, name='mission_detail'),
    path('mission_detail/<int:mission_id>/mission_scrap', views.mission_scrap, name='mission_scrap'),
    path('mission_detail/<int:mission_id>/mission_scrap_del', views.mission_scrap_del, name='mission_scrap_del'),
    path('mission_create/', views.mission_create, name='mission_create'),
    path('mission_delete/<int:mission_id>', views.mission_delete, name='mission_delete'),
    path('mission_comment_create/<int:mission_id>', views.mission_comment_create, name='mission_comment_create'),
    path('mission_comment_delete/<int:comment_id>', views.mission_comment_delete, name='mission_comment_delete'),
    path('mission_pick/<int:comment_id>', views.mission_pick, name="mission_pick"),
    path('commenting/<int:pk>', views.commenting, name= 'commenting'),
    path('comment_like/<int:pk>', views.comment_like, name='like'),
    path('mission_comment_like/<int:comment_id>', views.mission_comment_like, name='mission_comment_like'),
    path('photowrite/', views.photowrite, name='photowrite'),
    path('contestwrite/', views.contestwrite, name='contestwrite'),
    path('contest/<int:contest_id>', views.contestlike, name='contestlike'),
    path('photo_search/', views.photo_search, name='photo_search'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from hackproject import settings
from two.models import *

# Create your models here.
class User(AbstractUser):
    nickname = models.CharField(max_length=100)
    profile = models.ImageField(upload_to='account/', blank=True, null=True)
    email = models.EmailField(max_length=200)
    info = models.TextField(max_length=200, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')
    point = models.IntegerField(default=100)
    
    pscraps = models.ManyToManyField(Photoshop, related_name="pscrap_users")
    mscraps = models.ManyToManyField(Mission, related_name="mscrap_users")

    ## 이메일 인증 시 true 값
    is_active = models.BooleanField(default=False)

    class Meta(object):
        unique_together = ('email',)

account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from hackproject import settings

User = get_user_model()

class LoginForm(AuthenticationForm):
    pass

class RegisterForm(UserCreationForm):
    birthday = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    class Meta:
        model = User
        fields = ['username', "nickname", "profile", "email", "info", "password1", "password2", "birthday"]

class UserEditForm(UserChangeForm):
    password = None
    birthday = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    class Meta:
        model = User
        fields = ['profile', 'nickname', 'info', 'birthday' ]

account/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model, login, authenticate, logout, update_session_auth_hash
from .forms import LoginForm, RegisterForm
from django.contrib.auth.forms import PasswordChangeForm
from .forms import UserEditForm
from django.core.paginator import Paginator
from django.contrib import messages

# 이메일 인증을 위한 import
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text

User = get_user_model()

# Create your views here.
def signin(request):
    if request.method == "POST":
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request=request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('home')
        else:
            username = form.data.get('username')
            if User.objects.filter(username=username):
                user = User.objects.get(username=username)
                if user and user.is_active == False: messages.warning(request, "이메일 인증 후 로그인 하세요!")
    else:
        form = LoginForm()
    return render(request, "signin.html", {"form":form})

def signup(request):
    if request.method == "POST":
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.is_active = False
            user.save()

            current_site = get_current_site(request) 
            # localhost:8000
            message = render_to_string('activate.html',                         {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).encode().decode(),
                'token': account_activation_token.make_token(user),
            })
            mail_subject = "[2%를 부탁해] 회원 가입을 위한 이메일 인증 메일입니다."
            user_email = user.email
            email = EmailMessage(mail_subject, message, to=[user_email])
            email.send()
            return HttpResponse(
                '<div style="font-size: 40px; width: 100%; height:100%; display:flex; text-align:center; '
                'justify-content: center; align-items: center;">'
                '입력한 이메일<span>로 인증 링크가 전송되었습니다.</span>'
                '</div>'
            )
            return redirect('home')
        print(messages.error(request, form.non_field_errors()))
    else:
        form = RegisterForm()
    return render(request, "signup.html", {"form":form})

def signout(request):
    logout(request)
    return redirect('home')


# 마이페이지 노출
def mypage(request):
    if not request.user.is_authenticated: return redirect('signin')
    d_user = request.user
    # photoshop scraps paginator
    photoshops = d_user.pscraps.all()
    p_paginator = Paginator(photoshops, 4)
    ppage = request.GET.get('page')
    photoscraps = p_paginator.get_page(ppage)
    # mission scraps paginator
    missions = d_user.mscraps.all()
    m_paginator = Paginator(missions, 4)
    mpage = request.GET.get('page')
    missionscraps = m_paginator.get_page(mpage)
    return render(request, 'mypage.html',{ 'd_user': d_user, 'photoscraps': photoscraps, 'missionscraps': missionscraps })

# 유저 페이지 노출
def user(request, username):
    d_user = get_object_or_404(User, username=username)
    # photoshop paginator
    photoshops = d_user.photoshop.all()
    p_paginator = Paginator(photoshops, 8)
    ppage = request.GET.get('page')
    photocut = p_paginator.get_page(ppage)
    # mission paginator
    missions = d_user.mission.all()
    m_paginator = Paginator(missions, 8)
    mpage = request.GET.get('page')
    missioncut = m_paginator.get_page(mpage)
    # mission comment paginator
    mission_comments = d_user.missionwriter.all()
    mc_paginator = Paginator(mission_comments, 8)
    mcpage = request.GET.get('page')
    commentcut = mc_paginator.get_page(mcpage)
    return render(request, 'user.html',{ 'd_user': d_user, 'photocut':photocut, 'missioncut': missioncut, 'commentcut': commentcut})

# 팔로잉 리스트 노출
def following(request, username):
    user = get_object_or_404(User, username=username)
    flist = user.followings.all()
    paginator = Paginator(flist, 5)
    page = request.GET.get('page')
    fusers = paginator.get_page(page)
    return render(request, 'flist.html', { 'fusers': fusers })

# 팔로워 리스트 노출
def follower(request, username):
    user = get_object_or_404(User, username=username)
    flist = user.followers.all()
    paginator = Paginator(flist, 5)
    page = request.GET.get('page')
    fusers = paginator.get_page(page)
    return render(request, 'flist.html', { 'fusers': fusers })

# 유저 팔로우 기능
def follow(request, username):
    # request.user -> user(username=username) 팔로우(request.user following 리스트에 user를 추가)
    user = get_object_or_404(User, username=username)
    if request.user != user:
        user.followers.add(request.user)
        user.save()
    return redirect('user', username=username)

# 유저 언팔 기능
def unfollow(request, username):
    # request.user -> user(username=usernam) 팔로우(request.user following 리스트에 user를 추가)
    user = get_object_or_404(User, username=username)
    if request.user != user:
        user.followers.remove(request.user)
        user.save()
    return redirect('user', username=username)

def info_setting(request): 
    if request.method == "GET":
        form = UserEditForm(instance=request.user)
    else:
        form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('mypage')
    return render(request, 'setting.html', { 'form': form })

def pw_setting(request):
    if request.method == "GET":
        form = PasswordChangeForm(user=request.user)
    else:
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('mypage')
    return render(request, 'setting.html', { 'form': form })


### 이메일 인증을 통한 유저 활성화 기능
def activate(request, uid64, token):
    uid = force_text(urlsafe_base64_decode(uid64))
    user = User.objects.get(pk=uid)
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('home')
    else:
        return HttpResponse('비정상적인 접근입니다.')

account/templates/account.html
<!-- signin / signup base template -->

<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
	{% endblock %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="/static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css?ver=1">
<!--===============================================================================================-->
</head>
<body>
	{% block content %}            
	{% endblock %}
<!--===============================================================================================-->
	<script src="/static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/daterangepicker/moment.min.js"></script>
	<script src="/static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/js/main.js"></script>

	<script>
		
		 $('#profile-input').on('change',function(){
			//get the file name
			var fileName = $('#profile-input')[0].files[0]['name'];
			if (fileName.length > 10){
				fileName = fileName.substring(0, 10) + "...";
			}
			//replace the "Choose a file" label
			$('#profile-label').html(fileName);
		});
	</script>

</body>
</html>

account/templates/activate.html
{% autoescape off %}
    <h3>2%를 부탁해</h3>
    <hr>
    <div>
        아래 링크를 클릭하면 이메일 인증이 완료됩니다.
        회원가입 링크 : http://{{ domain }}{% url 'activate' uid64=uid token=token %}
    </div>

{% endautoescape %}

account/templates/flist.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" href="/static/main/css/home.css"> -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@200;300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- jQuery Modal -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
    <style>
    body {font-family: 'Noto Serif KR', serif;}
    h1, h2, h3, h4, h5, h6 {
        font-family: 'Noto Serif KR', serif;
        letter-spacing: 0px;
    }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>
    <!-- following / follower list popup page -->
    <div class="w3-container w3-content">
        <table class="w3-padding-32">
            {% for fuser in fusers %}
            <tr>
                <td>
                    <div style="margin-bottom: 1rem; width: 100px; height: 100px; text-align:center;">
                        <a href="{% url 'user' fuser.username %}" style="text-decoration: none;">
                            {% if fuser.profile %}
                                <div style="overflow: hidden; width: 100%; height: 100%;  border-radius: 50%;">
                                    <img src="{{ fuser.profile.url}}">
                                </div>
                            {% else %}
                                <div style="overflow: hidden; width: 100%; height: 100%;  border-radius: 50%; border-style: solid;">
                                    <i class="fa fa-user" style="font-size: 7rem;"></i>
                                </div>
                            {% endif %}
                        </a>
                    </div>
                </td>
                <td style="margin-bottom: 1rem; padding-left: 2rem;">
                    <a href="{% url 'user' fuser.username %}" style="text-decoration: none;">
                        <div style="vertical-align: middle;">
                            <h3>{{ fuser.username }}</h3>
                            <h6><i>{{ fuser.email }}</i></h6>
                        </div>
                    </a>
                </td>
            </tr>
            {% empty %}
                empty list
            {% endfor %}
        </table>
    </div>
    <!-- Pagination -->
    <div class="w3-container w3-center w3-padding-32">
        <div class="w3-bar">
            {% if fusers.has_previous %}
                <a href="?page={{fusers.previous_page_number}}" class="w3-bar-item w3-button w3-hover-black">«</a>
            {% endif %}
            <span class="w3-bar-item">{{ fusers.number }}</span>
            <span class="w3-bar-item">/</span>
            <span class="w3-bar-item">{{ fusers.paginator.num_pages }}</span>
            {%if fusers.has_next%}
                <span><a href="?page={{fusers.next_page_number}}" class="w3-bar-item w3-button w3-hover-black">»</a></span>
            {%endif%}
        </div>
    </div>


</body>
</html>

account/templates/sample_popol.html
<!DOCTYPE html>
<html lang="en">
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
.w3-third img{margin-bottom: -6px; opacity: 0.8; cursor: pointer}
.w3-third img:hover{opacity: 1}
</style>
<body class="w3-light-grey w3-content" style="max-width:1600px">

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-bar-block w3-white w3-animate-left w3-text-grey w3-collapse w3-top w3-center" style="z-index:3;width:300px;font-weight:bold" id="mySidebar"><br>


    <!-- 유저 프로필 이미지 -->
    {% if d_user.profile %}
        <img src="{{ d_user.profile.url}}">
    {%else%}
        <img src="{% static 'default_profile.jpg' %}">
    {%endif%}

    <h3 class="w3-padding-64 w3-center">{{ d_user.username }}</h3>
    <h6 class="w3-padding-64 w3-center">{{ d_user.info }}</h6>

    <!-- 유저 팔로우 기능 -->
    {% if user.is_authenticated %}
    <!-- 자기 자신이 아니면: 로그인한 유저와 유저 페이지의 유저가 일치하지 않을 때 -->
    {% if request.user != d_user %}
        <!-- 언팔로우 노출 : 이미 팔로우한 유저일 때 -->
        {% if request.user in d_user.followers.all %}
            <a href="{% url 'unfollow' d_user.username %}">UNFOLLOW</a>
        {% else %} <!-- 팔로우 노출 : 팔로우 하지 않는 유저일 때 -->
            <a href="{% url 'follow' d_user.username %}">FOLLOW</a>
        {% endif %}
    {% else %} <!-- 자신의 유저 페이지이면 -->
        <a href="{% url 'mypage' %}"></a>
    {% endif %}
    {% else %} <!-- 로그인 안 했으면 -->
        <!-- 팔로우인 척 하면서 로그인 페이지로 이동 -->
        <a href="{% url 'signin' %}">FOLLOW</a>
    {% endif %}

    <!-- 유저 팔로우/팔로잉 수 노출 -->
    <div role="followers">
    <a href="{% url 'follower' d_user.username %}">{{ d_user.followers.count }} followers</a>
    </div>
    <div role="followings">
    <a href="{% url 'following' d_user.username %}">{{ d_user.followings.count }} followings</a>
    </div>

  <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-padding w3-hide-large">CLOSE</a>
  <a href="#PHOTOSHOP" onclick="w3_close()" class="w3-bar-item w3-button">PHOTOSHOP</a> 
  <a href="#mission" onclick="w3_close()" class="w3-bar-item w3-button">MISSION</a> 
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-white w3-xlarge w3-padding-16">
  <span class="w3-left w3-padding">{{ d_user.username }}</span>
  <a href="javascript:void(0)" class="w3-right w3-button w3-white" onclick="w3_open()">☰</a>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px">

    <!-- Push down content on small screens --> 
    <div class="w3-hide-large" style="margin-top:83px"></div>
  
    <!--------------------------------------------
    *               작성한 보정법              *
    ------------------------------------------->
    <div role="photoshop" class="w3-row">
        <div class="w3-third">
            {% for p in d_user.photoshop.all %}
                <div class="container"> <!-- ???? -->
                    <div class="col-md-3 px-0">
                        <a href="{% url 'photodetail' p.id %}" style="display: none;">{{ p.date }}</a>
                        <img src="{{ p.photoafter.url }}" alt="{{ p.title }}" style="object-fit: contain;
                        max-width: 100%;
                        max-height: 100%;
                        width: auto;
                        height: auto;">
                        <span style="display: none;">{{ p.getlike }}</span>
                    </div>
                </div>
                <!-- if last column in row -->
                {% if forloop.counter | divisibleby:"3" and not forloop.last %}
                    </div><div class="w3-third">
                {% endif %}
            {% endfor %}
        </div>
        
    </div>

    <!-------------------------------------
    *               의뢰글                *
    -------------------------------------->
    <div role="mission" class="w3-third">
      <img src="/w3images/boy.jpg" style="width:100%" onclick="onClick(this)" alt="Quiet day at the beach. Cold, but beautiful">
      <img src="/w3images/man_bench.jpg" style="width:100%" onclick="onClick(this)" alt="Waiting for the bus in the desert">
      <img src="/w3images/natureboy.jpg" style="width:100%" onclick="onClick(this)" alt="Nature again.. At its finest!">
    </div>
    
    <div class="w3-third">
      <img src="/w3images/girl.jpg" style="width:100%" onclick="onClick(this)" alt="Canoeing again">
      <img src="/w3images/girl_train.jpg" style="width:100%" onclick="onClick(this)" alt="A girl, and a train passing">
      <img src="/w3images/closegirl.jpg" style="width:100%" onclick="onClick(this)" alt="What a beautiful day!">
    </div>

  <!-- 작성한 의뢰글 -->
<h3># 작성한 의뢰글</h3>
<div role="mission">
{% for mission in d_user.mission.all %}
    <a href="{% url 'mission_detail' mission.id %}">
        <p>{{ mission.title }}</p>
        <p>{{ mission.pub_date }}</p>
    </a>
{% endfor %}
</div>

<!-- 작성한 답변글 -->
<h3># 작성한 답변글</h3>
<div role="missionComment">
{% for mc in d_user.missionwriter.all %}
    <a href="{% url 'mission_detail' mc.mission.id %}">
        {% if mc.image %}<img src="{{ mc.image.url }}">{% endif %}
        <p>{{ mc.pub_date }}</p>
    </a>
{% endfor %}
</div>

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="#" class="w3-bar-item w3-button w3-hover-black">«</a>
      <a href="#" class="w3-bar-item w3-black w3-button">1</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">»</a>
    </div>
  </div>
  
  <!-- Modal for full size images on click-->
  <div id="modal01" class="w3-modal w3-black" style="padding-top:0" onclick="this.style.display='none'">
    <span class="w3-button w3-black w3-xlarge w3-display-topright">×</span>
    <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
      <img id="img01" class="w3-image">
      <a id="img_link" href="#"><p id="caption"></p><p id="caption_date"></p></a>
    </div>
  </div>

<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption"); // 모달창
  var captionDate = document.getElementById("caption_date"); // 모달창
  var hyperLink = document.getElementById("img_link"); //모달창
  var goTo = element.prev(); // 게시글 링크 객체(a 태그)
  captionText.innerHTML = element.alt; // 모달창 내용 표기
  captionDate.innerHTML = "♥ " + element.next().text(); // 모달창 날짜 표기
  hyperLink.prop('href', goTo.attr('href')); // 모달창 링크 설정
}

</script>


</body>
</html>

account/templates/setting.html
{% extends 'base.html' %}

{% block title %}
<title>Profile Settings</title>
<style>
    input {
        width: 100%;
        padding: 0.5rem;
    }
    textarea {
        width: 100%;
        padding: 0.5rem;
    }

    label {
        margin-right: 1rem;
        text-align: left;
    }

    td {
        width: 100%;
    }

</style>
{% endblock %}

{% block content %}
<div class="w3-container">
    <div class="w3-content w3-padding-32">
            <form method="POST" enctype="multipart/form-data">
                {%csrf_token%}
                <table class="form_table">{{form.as_table}}</table>
                <br>
                <button id="edit-btn" class="w3-button w3-dark-gray" type="submit">프로필 변경</button>
                <a class="w3-button w3-gray w3-text-white" href=" {%url 'mypage' %} ">변경 취소</a>
                <a class="w3-button w3-gray w3-text-white" href=" {%url 'home' %} ">메인 화면</a>
            </form>
    </div>
</div>

<script src="http://code.jquery.com/jquery-latest.js"></script>
<script>
    
    $(document).ready(function(e) {
        $('input').each(function(element) {
            $(element).addClass('w3-input');
            $(element).addClass('w3-padding-16');
        });
        $('textarea').each(function(element) {
            $(element).addClass('w3-input');
            $(element).addClass('w3-padding-16');
        });

        $("#id_birthday").prop("type", "date");
    });
</script>

{% endblock %}

account/templates/settings.html
<section role="user_settings">
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <table class="form_table">{{form.as_table}}</table>
        <br>
        <button id="edit-btn" class="btn btn-primary btn-lg" type="submit">내용 변경</button>
        <a class="btn btn-outline-dark btn-lg" href=" {%url 'mypage' %} ">변경 취소</a>
        <a class="btn btn-dark btn-lg" href=" {%url 'home' %} ">메인 화면</a>
    </form>
</section>